SELECT USER
FROM DUAL;
------------------
SELECT *
FROM QUESTION;

DESC QUESTION;
/*
이름          널?       유형            
----------- -------- ------------- 
QUESTION_ID NOT NULL VARCHAR2(30)  
E_TYPE_ID   NOT NULL VARCHAR2(30)  
Q_CONTENT   NOT NULL VARCHAR2(100) 
POINT       NOT NULL NUMBER        
*/

--QUESTION테이블 시퀀스 생성 SEQ_QUESTION
CREATE SEQUENCE SEQ_QUESTION
NOCACHE;
--Sequence SEQ_QUESTION이(가) 생성되었습니다.

COMMIT;

--EVALUATE_TYPE테이블 시퀀스 생성 SEQ_EVALUATE_TYPE
CREATE SEQUENCE SEQ_EVALUATE_TYPE
NOCACHE;
--Sequence SEQ_EVALUATE_TYPE이(가) 생성되었습니다.

COMMIT;


DESC EVALUATE_TYPE;

--EVALUATE_TYPE테이블 데이터 입력
INSERT INTO EVALUATE_TYPE(E_TYPE_ID, E_TYPE_NAME)
VALUES (SEQ_EVALUATE_TYPE.NEXTVAL, '리더십 점수');

INSERT INTO EVALUATE_TYPE(E_TYPE_ID, E_TYPE_NAME)
VALUES (SEQ_EVALUATE_TYPE.NEXTVAL, '매너 점수');

INSERT INTO EVALUATE_TYPE(E_TYPE_ID, E_TYPE_NAME)
VALUES (SEQ_EVALUATE_TYPE.NEXTVAL, '체력 점수');

-- 확인
SELECT *
FROM EVALUATE_TYPE;
/*
1	리더십 점수
2	매너 점수
3	체력 점수
*/

COMMIT;

-- QUESTION 테이블 데이터 입력
INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 2 , '가장 친절한 사람은 누구인가요?', 1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 2 , '가장 불친절한 사람은 누구인가요?', -1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 2 , '위험하게 라이딩한 사람은 누구인가요?', -1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 1 , 'GOOD', 1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 1 , 'SOSO', 0);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 1 , 'BAD', -1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 3 , '완주하지 못한 사람은 누구인가요?', -1);

INSERT INTO QUESTION(QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT)
VALUES(SEQ_QUESTION.NEXTVAL, 3 , '실제 난이도에 못 미친 사람은 누구인가요?', -1);

-- 확인
SELECT QUESTION_ID, E_TYPE_ID, Q_CONTENT, POINT
FROM QUESTION;

DESC QUESTION;
/*
1	2	가장 친절한 사람은 누구인가요?	1
2	2	가장 불친절한 사람은 누구인가요?	-1
3	2	위험하게 라이딩한 사람은 누구인가요?	-1
4	1	GOOD	1
5	1	SOSO	0
6	1	BAD	-1
7	3	완주하지 못한 사람은 누구인가요?	-1
8	3	실제 난이도에 못 미친 사람은 누구인가요?	-1
*/

COMMIT;

-- 바티스 활용(질문 문항들 가져오기)
SELECT Q_CONTENT
FROM QUESTION;
--> 한 줄 구성
SELECT Q_CONTENT FROM QUESTION


-- 시퀀스 필요
SELECT *
FROM EVALUATION_GRADE;

SELECT *
FROM CONTRIBUTION_GRADE;

----------------시퀀스 생성
CREATE SEQUENCE SEQ_EVALUATION_GRADE
NOCACHE;
-- Sequence SEQ_EVALUATION_GRADE이(가) 생성되었습니다.
CREATE SEQUENCE SEQ_CONTRIBUTION_GRADE
NOCACHE;
-- Sequence SEQ_CONTRIBUTION_GRADE이(가) 생성되었습니다.

--------------- 데이터입력
DESC EVALUATION_GRADE;
INSERT INTO EVALUATION_GRADE(E_GRADE_ID, GRADE_NAME)
VALUES(SEQ_EVALUATION_GRADE.NEXTVAL, '다이아전거');
INSERT INTO EVALUATION_GRADE(E_GRADE_ID, GRADE_NAME)
VALUES(SEQ_EVALUATION_GRADE.NEXTVAL, '금전거');
INSERT INTO EVALUATION_GRADE(E_GRADE_ID, GRADE_NAME)
VALUES(SEQ_EVALUATION_GRADE.NEXTVAL, '은전거');
INSERT INTO EVALUATION_GRADE(E_GRADE_ID, GRADE_NAME)
VALUES(SEQ_EVALUATION_GRADE.NEXTVAL, '동전거');
INSERT INTO EVALUATION_GRADE(E_GRADE_ID, GRADE_NAME)
VALUES(SEQ_EVALUATION_GRADE.NEXTVAL, '돌전거');

--확인
SELECT *
FROM EVALUATION_GRADE;
/*
1	다이아전거
2	금전거
3	은전거
4	동전거
5	돌전거
*/

DROP SEQUENCE SEQ_CONTRIBUTION_GRADE;



DESC CONTRIBUTION_GRADE;

INSERT INTO CONTRIBUTION_GRADE(C_GRADE_ID, GRADE_NAME)
VALUES(SEQ_CONTRIBUTION_GRADE.NEXTVAL, '다이아헬멧');
INSERT INTO CONTRIBUTION_GRADE(C_GRADE_ID, GRADE_NAME)
VALUES(SEQ_CONTRIBUTION_GRADE.NEXTVAL, '금헬멧');
INSERT INTO CONTRIBUTION_GRADE(C_GRADE_ID, GRADE_NAME)
VALUES(SEQ_CONTRIBUTION_GRADE.NEXTVAL, '은헬멧');
INSERT INTO CONTRIBUTION_GRADE(C_GRADE_ID, GRADE_NAME)
VALUES(SEQ_CONTRIBUTION_GRADE.NEXTVAL, '동헬멧');


SELECT *
FROM CONTRIBUTION_GRADE;

COMMIT;



--------------------------------------------------------------------------------
-- 마이페이지에서 보여주는 요소 
-- 회원프로필아이콘, 이메일, 닉네임
-- ================= ======= =======
--   PROFILE_IMG     PROFILE  PROFILE

-- 한마디, 매너등급,                     공헌도 등급
-- ======  ========                      =============
-- PROFILE  EVALUATION_GRADE               CONTRIBUTION_GRADE

SELECT *
FROM USER_TABLES;

SELECT *
FROM MEMBER;

SELECT *
FROM PROFILE
WHERE USER_ID=2;

SELECT *
FROM PROFILE_IMG;


SELECT *
FROM CONTRIBUTION_GRADE;


SELECT *
FROM EVALUATION_GRADE;

--------------------------------------------------------------------------------
-- 마이페이지에서 보여주는 요소 
-- 회원프로필아이콘, 이메일, 닉네임
-- ================= ======= =======
--   PROFILE_IMG     PROFILE  PROFILE

-- 한마디, 매너등급,                     공헌도 등급
-- ======  ========                      =============
-- PROFILE  EVALUATION_GRADE               CONTRIBUTION_GRADE


SELECT P.USER_ID AS USER_ID
    ,P.EMAIL AS EMAIL
    ,P.NICKNAME AS NICKNAME
    ,P.ONEWORD AS ONEWORD
    ,PI.PI_ADDRESS
FROM
(
    SELECT USER_ID ,EMAIL, NICKNAME
    , NVL(INTRODUCE,' ') AS ONEWORD
    , PIMG_ID
    FROM PROFILE
    WHERE USER_ID = 2
)P JOIN PROFILE_IMG PI
ON P.PIMG_ID = PI.PIMG_ID;

-- 마이페이지 뷰 생성
/*
CREATE OR REPLACE VIEW VIEW_MYPAGEMAIN
AS
SELECT P.USER_ID AS USER_ID
    ,P.EMAIL AS EMAIL
    ,P.NICKNAME AS NICKNAME
    ,P.ONEWORD AS ONEWORD
    ,PI.PI_ADDRESS
FROM
(
    SELECT USER_ID ,EMAIL, NICKNAME
    , NVL(INTRODUCE,' ') AS ONEWORD
    , PIMG_ID
    FROM PROFILE
    WHERE USER_ID = 2
)P JOIN PROFILE_IMG PI
ON P.PIMG_ID = PI.PIMG_ID;

-- 마이페이지 뷰 완성
SELECT USER_ID, EMAIL, NICKNAME, ONEWORD, PI_ADDRESS
FROM VIEW_MYPAGEMAIN;
*/
DROP VIEW VIEW_MYPAGEMAIN;

COMMIT;

-- 회원생성코드 받으면 SELECT 하는 프로시저 생성
-- EXEC PRC_MYPAGE_S('2')
-- !! 프로시저 안에서 SELECT 문은 커서 !! 
/*
CREATE OR REPLACE PROCEDURE PRC_MYPAGE_S
(V_USER_ID  IN MEMBER.USER_ID%TYPE)
IS
BEGIN
    SELECT P.USER_ID AS USER_ID
    ,P.EMAIL AS EMAIL
    ,P.NICKNAME AS NICKNAME
    ,P.ONEWORD AS ONEWORD
    ,PI.PI_ADDRESS
    FROM
    (
        SELECT USER_ID ,EMAIL, NICKNAME
        , NVL(INTRODUCE,' ') AS ONEWORD
        , PIMG_ID
        FROM PROFILE
        WHERE USER_ID = V_USER_ID
    )P JOIN PROFILE_IMG PI
    ON P.PIMG_ID = PI.PIMG_ID
END;
*/  
--------------------------------------------------------------------------------
-- 마이페이지에서 등급 보여주기 
-- 프로시저 만들기
-- 1. 평가기록 테이블 (EVALUATION_RECORD)
--    에서 참여한 회원정보ID


COMMIT;

--------------------------------------------------------------------------------
COMMIT;
-- 마이페이지에서 등급 보여주기 
-- 평가기록 테이블에서 점수 누적해서 if 문 돌리기
SELECT *
FROM EVALUATION_RECORD;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_EVALUATION_RECORD
NOCACHE;
--Sequence SEQ_EVALUATION_RECORD이(가) 생성되었습니다.

SELECT *
FROM RIDING;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_RIDING
NOCACHE;
--Sequence SEQ_RIDING이(가) 생성되었습니다.

SELECT *
FROM PARTICIPATED_MEMBER;

--시퀀스 생성
CREATE SEQUENCE SEQ_PARTICIPATED_MEMBER
NOCACHE;
--Sequence SEQ_PARTICIPATED_MEMBER이(가) 생성되었습니다.


COMMIT;

DESC USER_SEQUENCES;

SELECT *
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_RIDING';

--------------------------------------------------------------------------------
-- 마이페이지에서 등급 보여주기 
-- 평가기록 테이블에서 점수 누적해서 if 문 돌리기
DESC PARTICIPATED_MEMBER;

SELECT P_MEMBER_ID
FROM PARTICIPATED_MEMBER
WHERE USER_ID = '2';

DESC EVALUATION_RECORD;

SELECT P_MEMBER_ID, 
FROM EVALUATION_RECORD
WHERE P_MEMBER_ID = (SELECT P_MEMBER_ID
                     FROM PARTICIPATED_MEMBER
                     WHERE USER_ID = '2');
                     
        

-----------------------------------------------------------------
-- 참여중인 라이딩 스타일 조회
-- 다인모임ID / 모임명 / 기간 / 모임상태 /
-- RIDING       RIDING   RIDING   RIDING  

DESC RIDING;

SELECT SYSDATE-48
FROM DUAL;

SELECT RIDING_ID, RIDING_NAME
    ,(START_DATE || END_DATE) AS DATE
    ,CASE WHEN START_DATE <= SYSDATE-48
FROM RIDING;


--------------------------------------------------------------------------------
--MYPAGEVIEW 생성
CREATE OR REPLACE VIEW VIEW_MYPAGEMAIN
AS
SELECT P.USER_ID AS USER_ID
    ,P.EMAIL AS EMAIL
    ,P.NICKNAME AS NICKNAME
    ,P.ONEWORD AS ONEWORD
    ,PI.PI_ADDRESS
FROM
(
    SELECT USER_ID ,EMAIL, NICKNAME
    , NVL(INTRODUCE,' ') AS ONEWORD
    , PIMG_ID
    FROM PROFILE
)P JOIN PROFILE_IMG PI
ON P.PIMG_ID = PI.PIMG_ID;
--View VIEW_MYPAGEMAIN이(가) 생성되었습니다.

--테스트
SELECT USER_ID,EMAIL,NICKNAME,ONEWORD,PI_ADDRESS
FROM VIEW_MYPAGEMAIN
WHERE USER_ID = '2';


COMMIT;

-----------------------------------------------------------------
-- 참여중인 라이딩 스타일 조회
-- 다인모임ID / 모임명 / 기간 / 모임상태 /
-- RIDING       RIDING   RIDING   RIDING  

DESC RIDING;

SELECT TO_DATE('2022-06-20 14:00:00','YYYY-MM-DD HH24:MI:SS') - 49/24
FROM DUAL;

SELECT RIDING_ID, RIDING_NAME
    ,(START_DATE || END_DATE) AS PERIOD
    ,CASE WHEN SYSDATE <= TO_DATE(START_DATE,'YYYY-MM-DD HH24:MI:SS') - 49/24 THEN '모임참가가능'
          WHEN SYSDATE <= TO_DATE(START_DATE,'YYYY-MM-DD HH24:MI:SS') - 48/24 THEN '준비요청기간'
          WHEN SYSDATE <= START_DATE THEN '준비요청기간'
          ELSE '알수없음'
          END STATUS
FROM RIDING;

CREATE OR REPLACE VIEW VIEW_PARTICIRIDING_LIST
AS
SELECT RIDING_ID, RIDING_NAME
    ,(START_DATE || END_DATE) AS PERIOD
    ,CASE WHEN SYSDATE <= TO_DATE(START_DATE,'YYYY-MM-DD HH24:MI:SS') - 49/24 THEN '모임참가가능'
          WHEN SYSDATE <= TO_DATE(START_DATE,'YYYY-MM-DD HH24:MI:SS') - 48/24 THEN '준비요청기간'
          WHEN SYSDATE <= START_DATE THEN '준비요청기간'
          ELSE '알수없음'
          END STATUS
FROM RIDING;

SELECT RIDING_ID, RIDING_NAME,PERIOD,STATUS
FROM VIEW_PARTICIRIDING_LIST;

COMMIT;

--------------------------------------------------------------------------------
--라이딩평가에서 문항가져오기    QUESTION    Q_CONTENT
SELECT Q_CONTENT
FROM QUESTION;

DESC QUESTION;
INSERT INTO QUESTION
VALUES(SEQ_QUESTION.NEXTVAL, 

--작성자 닉네임가져오기      
SELECT NICKNAME
FROM PROFILE
WHERE USER_ID=2;

-- 00 참여자가 참여한 라이딩 모임의 이름 알아오기
--모임이름 가져오기             ANSWER_DETAIL   
SELECT RIDING_NAME
FROM RIDING R JOIN PROFILE P JOIN PARTICIPATED_MEMBER PM
ON P.USER_ID = PM.USER_ID
ON PM.RIDING_ID = R.RIDING_ID
WHERE P.USER_ID = 2;

-- 00모임의 참여자명단 가져오기(닉네임으로)
SELECT PM.USER_ID AS USER_ID
    ,P.NICKNAME AS NICKNAME
FROM PARTICIPATED_MEMBER PM JOIN PROFILE P
ON PM.USER_ID = P.USER_ID
WHERE RIDING_ID = (SELECT RIDING_ID
                   FROM RIDING
                   WHERE RIDING_ID = 100);
                   
                   
DESC RIDING;

SELECT *
FROM RIDING;


--------------------------------------------------------------------------------
-- 라이딩 모임 데이터 입력
/*
이름             널?       유형            
-------------- -------- ------------- 
RIDING_ID      NOT NULL VARCHAR2(30)  
LEADER_ID      NOT NULL VARCHAR2(30)  
STEP_ID        NOT NULL NUMBER(1)     
SPEED_ID       NOT NULL NUMBER(1)     
MOOD_P_ID      NOT NULL NUMBER(1)     
DINING_P_ID    NOT NULL NUMBER(1)     
EAT_P_ID       NOT NULL NUMBER(1)     
AGE_P_ID       NOT NULL CHAR(1)       
SEX_P_ID       NOT NULL CHAR(1)       
E_GRADE_ID     NOT NULL NUMBER(1)     
RIDING_NAME    NOT NULL VARCHAR2(300) 
START_DATE     NOT NULL DATE          
END_DATE       NOT NULL DATE          
CREATED_DATE   NOT NULL DATE          
MAXIMUM        NOT NULL NUMBER(1)     
MEET_LATI      NOT NULL VARCHAR2(500) 
MEET_LONGI     NOT NULL VARCHAR2(500) 
MEET_ADDRESS   NOT NULL VARCHAR2(500) 
MEET_DETAIL    NOT NULL VARCHAR2(500) 
START_LATI     NOT NULL VARCHAR2(500) 
START_LONGI    NOT NULL VARCHAR2(500) 
START_ADDRESS  NOT NULL VARCHAR2(500) 
START_DETAIL   NOT NULL VARCHAR2(500) 
END_LATI       NOT NULL VARCHAR2(500) 
END_LONGI      NOT NULL VARCHAR2(500) 
END_ADDRESS    NOT NULL VARCHAR2(500) 
DETAIL_ADDRESS NOT NULL VARCHAR2(500) 
CONFIRM_DATE            DATE
*/

SELECT *
FROM USER_SEQUENCES;

INSERT INTO RIDING
VALUES(SEQ_RIDING.NEXTVAL, '2'
    , 1,1,1,1,1,'0','0',1
    ,'달려라'
    ,TO_DATE('2022-07-07','YYYY-MM-DD'),TO_DATE('2022-07-09','YYYY-MM-DD')
    ,SYSDATE,4
    ,'1234','1234','홍대입구역','탐앤탐스'
    ,'5678','5678','한강','한강gs앞'
    ,'1010','1010','풍성빌딩','풍성빌딩4층',NULL);

SELECT *
FROM SEX_PREFERENCE;

SELECT *
FROM RIDING;

SELECT *
FROM PARTICIPATED_MEMBER;

COMMIT;

INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'2','1',SYSDATE);


COMMIT;



-- 00모임의 참여자명단 가져오기(닉네임으로)
SELECT PM.USER_ID AS USER_ID
    ,P.NICKNAME AS NICKNAME
FROM PARTICIPATED_MEMBER PM JOIN PROFILE P
ON PM.USER_ID = P.USER_ID
WHERE RIDING_ID = (SELECT RIDING_ID
                   FROM RIDING
                   WHERE RIDING_ID = 1);
                   
COMMIT;



INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'2','1',SYSDATE);

SELECT *
FROM MEMBER;
/*
10
11
12
13
14
15
*/

INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'10','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'11','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'12','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'13','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'14','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'15','1',SYSDATE);

SELECT *
FROM PARTICIPATED_MEMBER;

COMMIT;

SELECT P.NICKNAME AS NICKNAME
		FROM PARTICIPATED_MEMBER PM JOIN PROFILE P
		ON PM.USER_ID = P.USER_ID
		WHERE RIDING_ID = (SELECT RIDING_ID
		                   FROM RIDING
		                   WHERE RIDING_ID = 1);
                           
SELECT P.NICKNAME AS NICKNAME
FROM PARTICIPATED_MEMBER PM JOIN PROFILE P JOIN RIDING R
ON PM.USER_ID = P.USER_ID
ON R.RIDING_ID = PM.RIDING_ID;

SELECT USER_ID
FROM PROFILE
WHERE USER_ID = 10;

SELECT USER_ID
FROM PARTICIPATED_MEMBER;



SELECT P.USER_ID
FROM PARTICIPATED_MEMBER PM JOIN PROFILE P
ON PM.USER_ID = P.USER_ID;

        
--------------------------------------------------------------------------------
-- 평가지 제출하면 insert 되는 쿼리(방장)
-- ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
-- CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
-- ANSWER_ATTENDANCE(출석체크응답내용) / ANSWER_ATTENDANCE / CHECK_ATTE_ID / P_MEMBER_ID(결석지목받은 사람)
-- ANSWER_DETAIL(응답내용) / ANS_DETAIL_ID / ANSWER_ID / QUESTION_ID / P_MEMBER_ID

-- 응답 내용(Q_CONTENT) == 질문(QUESTION)의 내용과 같을 때, 질문ID 얻어야함

DESC QUESTION;

SELECT QUESTION_ID, Q_CONTENT
FROM QUESTION;

-- 평가 제출 프로시저 생성
-- '체리','2','온풀','없음','없음',',사과','참외','수박'
CREATE OR REPLACE PROCEDURE PRC_QUESTION_I
( V_NICKNAME         IN PROFILE.NICKNAME%TYPE  
, V_RIDING_ID        IN RIDING.RIDING_ID%TYPE
, V_ATTENDANCE       IN PROFILE.NICKNAME%TYPE  
, V_KINDNESS        IN PROFILE.NICKNAME%TYPE  
, V_NOTKINDENESS    IN PROFILE.NICKNAME%TYPE  
, V_DANGERRIDING    IN PROFILE.NICKNAME%TYPE  
, V_NOTCOMPLETION   IN PROFILE.NICKNAME%TYPE  
, V_DIFFERENT       IN PROFILE.NICKNAME%TYPE  
)
IS
USER_ID             MEMBER.USER_ID%TYPE;
ATTENDANCE_ID       MEMBER.USER_ID%TYPE;
KINDNESS_ID         MEMBER.USER_ID%TYPE;
NOTKINDENESS_ID      MEMBER.USER_ID%TYPE;
DANGERRIDING_ID      MEMBER.USER_ID%TYPE;
NOTCOMPLETION_ID     MEMBER.USER_ID%TYPE;
DIFFERENT_ID         MEMBER.USER_ID%TYPE;

S_CHECK_ID          CHECK_ATTENDANCE.CHECK_ATTE_ID%TYPE;  
BEGIN
    -- 평가지 제출자 이름으로 USER_ID 찾기
    SELECT USER_ID  INTO USER_ID
    FROM PROFILE
    WHERE NICKNAME = V_NICKNAME;
    
    -- 결석자 닉네임으로 USER_ID 찾기
    
    SELECT USER_ID INTO ATTENDANCE_ID
    FROM PROFILE
    WHERE NICKNAME = V_ATTENDANCE;
    
    -- 친절한 사람 닉네임으로 USER_ID 찾기
    SELECT USER_ID INTO KINDNESS_ID
    FROM PROFILE
    WHERE NICKNAME = V_KINDNESS;
    
     -- 불친절한 사람 닉네임으로 USER_ID 찾기
    SELECT USER_ID INTO NOTKINDENESS_ID
    FROM PROFILE
    WHERE NICKNAME = V_NOTKINDENESS;
    
     -- 위험한 라이딩 한 사람 닉네임으로 USER_ID 찾기
    SELECT USER_ID INTO DANGERRIDING_ID
    FROM PROFILE
    WHERE NICKNAME = V_DANGERRIDING;
    
     -- 완주 못한 사람 닉네임으로 USER_ID 찾기
    SELECT USER_ID INTO NOTCOMPLETION_ID
    FROM PROFILE
    WHERE NICKNAME = V_NOTCOMPLETION;
    
     -- 실제 숙련도랑 다른 사람 닉네임으로 USER_ID 찾기
    SELECT USER_ID INTO DIFFERENT_ID
    FROM PROFILE
    WHERE NICKNAME = V_DIFFERENT;

   
    -- ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
    INSERT INTO ANSWER(ANSWER_ID,P_MEMBER_ID,SUBMIT_DATE)
    VALUES(SEQ_ANSWER.NEXTVAL,USER_ID,SYSDATE);
    
    -- CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
    INSERT INTO CHECK_ATTENDANCE(CHECK_ATTE_ID ,P_MEMBER_ID ,SUBMIT_DATE)
    VALUES(SEQ_CHECK_ATTENDANCE.NEXTVAL, USER_ID,SYSDATE);
    
    -- 출석체크 아이디 찾기
    SELECT CHECK_ATTE_ID INTO S_CHECK_ID
    FROM CHECK_ATTENDANCE
    WHERE P_MEMBER_ID = USER_ID;
    
    
    -- ANSWER_ATTENDANCE(출석체크응답내용) / ANSWER_ATTENDANCE / CHECK_ATTE_ID / P_MEMBER_ID(결석지목받은 사람)
    INSERT INTO ANSWER_ATTENDANCE(ANS_ATTE_ID ,CHECK_ATTE_ID ,P_MEMBER_ID)
    VALUES(SEQ_ANSWER_ATTENDANCE.NEXTVAL, S_CHECK_ID, USER_ID);
    
    COMMIT;
    
END;





--------------------------------------------------------------------------------
SELECT *
FROM USER_SEQUENCES;

CREATE SEQUENCE SEQ_ANSWER
NOCACHE;

CREATE SEQUENCE SEQ_CHECK_ATTENDANCE
NOCACHE;

DESC ANSWER;

DESC CHECK_ATTENDANCE;

DESC ANSWER_ATTENDANCE;

CREATE SEQUENCE SEQ_ANSWER_ATTENDANCE
NOCACHE;


-- 프로시저 확인
EXEC PRC_QUESTION_I('체리','2','온풀','없음','없음','사과','참외','수박');

COMMIT;
------------------------------------------------------------------

-- 평가 제출하면 따로따로 해야함. 작성자 --> 응답 / 출석체크
-- 참여한 회원 USER_ID
CREATE OR REPLACE PROCEDURE PRC_QUESTION_I
( V_USER_ID  IN MEMBER.USER_ID%TYPE )
IS  
BEGIN
    -- ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
    INSERT INTO ANSWER(ANSWER_ID,P_MEMBER_ID,SUBMIT_DATE)
    VALUES(SEQ_ANSWER.NEXTVAL,V_USER_ID,SYSDATE);
    
    -- CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
    INSERT INTO CHECK_ATTENDANCE(CHECK_ATTE_ID ,P_MEMBER_ID ,SUBMIT_DATE)
    VALUES(SEQ_CHECK_ATTENDANCE.NEXTVAL, V_USER_ID,SYSDATE);
    
    COMMIT;
END;


EXEC PRC_QUESTION_I('10');

SELECT *
FROM PARTICIPATED_MEMBER;

SELECT *
FROM ANSWER;



SELECT *
FROM CHECK_ATTENDANCE;

COMMIT;


--------------------------------------------------------------------------------
-- 평가 프로세스 할일
-- 필요한 쿼리문
-- 1. 평가기간인 모임이 있는지 SELECT
-- 2. 방장인지 아닌지 체크하는 SELECT 
-- 3. 문항 가져오는 쿼리(참여자일 때는 리더십에 관한 문항 추가!) ㅇㅋ
-- 4. 모임명 가져오는 쿼리ㅇㅋ
-- 5. 작성자 닉네임 가져오는 쿼리ㅇㅋ
-- 6. 참여자 명단 가져오는 쿼리ㅇㅋ
-- 7. 이미 제출했는지 확인하는 쿼리

-- 7. insert 하는 쿼리
--    응답 / 출석체크 / 출석체크응답내용 / 응답내용 
-- ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
-- CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
-- ANSWER_ATTENDANCE(출석체크응답내용) / ANSWER_ATTENDANCE / CHECK_ATTE_ID / P_MEMBER_ID(결석지목받은 사람)
-- ANSWER_DETAIL(응답내용) / ANS_DETAIL_ID / ANSWER_ID / QUESTION_ID / P_MEMBER_ID

--------------------------------------------------------------------------------
-- 3. 문항 가져오는 쿼리(참여자일 때는 리더십에 관한 문항 추가!)

--라이딩평가에서 문항가져오기    QUESTION    Q_CONTENT
SELECT QUESTION_ID , Q_CONTENT
FROM QUESTION;
-- 5. 작성자 닉네임 가져오는 쿼리
--작성자 닉네임가져오기      
SELECT USER_ID,NICKNAME
FROM PROFILE
WHERE USER_ID=2;
-- 4. 모임명 가져오는 쿼리
-- 00 참여자가 참여한 라이딩 모임의 이름 알아오기
--모임이름 가져오기             ANSWER_DETAIL   
SELECT R.RIDING_ID,R.RIDING_NAME
FROM RIDING R JOIN PROFILE P JOIN PARTICIPATED_MEMBER PM
ON P.USER_ID = PM.USER_ID
ON PM.RIDING_ID = R.RIDING_ID
WHERE P.USER_ID = 2;
-- 6. 참여자 명단 가져오는 쿼리
-- 00모임의 참여자명단 가져오기(닉네임으로)
SELECT PM.USER_ID AS USER_ID
    ,P.NICKNAME AS NICKNAME
FROM PARTICIPATED_MEMBER PM JOIN PROFILE P
ON PM.USER_ID = P.USER_ID
WHERE RIDING_ID = '1';
                   
SELECT     
FROM PARTICIPATED_MEMBER
WHERE TO_NUMBER(USER_ID) BETWEEN 10 AND 15;

COMMIT;
                  
SELECT *
FROM RIDING;

SELECT *
FROM PARTICIPATED_MEMBER;

SELECT *
FROM PROFILE
WHERE TO_NUMBER(USER_ID) BETWEEN 10 AND 15;

SELECT *
FROM MEMBER
WHERE TO_NUMBER(USER_ID) BETWEEN 10 AND 15;

--데이터입력
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'10','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'11','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'12','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'13','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'14','1',SYSDATE);
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL,'15','1',SYSDATE);


COMMIT;

--PROFIE 테이블 데이터 입력 USER_ID 10 ~ 15
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 10, 0, 0, 1
     , 0, 0, 0, 'eh1@gmail.com', '1999-07-01', 'f', 'eh1', '은혜1');
     
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 11, 0, 0, 1
     , 0, 0, 0, 'eh2@gmail.com', '1998-07-02', 'f', 'eh2', '은혜2');
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 12, 0, 0, 1
     , 0, 0, 0, 'eh3@gmail.com', '1997-07-02', 'f', 'eh3', '은혜3');
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 13, 0, 0, 1
     , 0, 0, 0, 'eh4@gmail.com', '1994-07-02', 'f', 'eh4', '은혜4');
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 14, 0, 0, 1
     , 0, 0, 0, 'eh5@gmail.com', '1989-07-02', 'f', 'eh5', '은혜5');
INSERT INTO PROFILE(PROFILE_ID, USER_ID, MOOD_P_ID, EAT_P_ID, PIMG_ID, DINING_P_ID, SEX_P_ID, AGE_P_ID, EMAIL, BIRTHDAY, SEX, PASSWORD, NICKNAME)
VALUES(SEQ_PROFILE.NEXTVAL, 15, 0, 0, 1
     , 0, 0, 0, 'eh6@gmail.com', '1988-07-02', 'f', 'eh6', '은혜6');
     
COMMIT;

--------------------------------------------------------------------------------
/*
1번 라이딩 모임에 참여한 사람들
2	온풀
10	은혜1
11	은혜2
12	은혜3
13	은혜4
14	은혜5
15	은혜6
*/

/*
참여자 명단 테이블
14	10	1	2022-06-16
15	11	1	2022-06-16
16	12	1	2022-06-16
17	13	1	2022-06-16
18	14	1	2022-06-16
19	15	1	2022-06-16
1	2	1	2022-06-15
*/
--  insert 하는 쿼리
--    응답 / 출석체크 / 출석체크응답내용 / 응답내용 
-- 1.ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
-- 2.CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
-- 3.ANSWER_ATTENDANCE(출석체크응답내용) / ANSWER_ATTENDANCE / CHECK_ATTE_ID / P_MEMBER_ID(결석지목받은 사람)
-- 4.ANSWER_DETAIL(응답내용) / ANS_DETAIL_ID / ANSWER_ID / QUESTION_ID / P_MEMBER_ID

-- 1.ANSWER (응답) ANSWER_ID / P_MEMBER_ID / SUBMIT_DATE
INSERT INTO ANSWER (ANSWER_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_ANSWER.NEXTVAL, 1,SYSDATE);

INSERT INTO ANSWER (ANSWER_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_ANSWER.NEXTVAL, 19,SYSDATE);
INSERT INTO ANSWER (ANSWER_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_ANSWER.NEXTVAL, 15,SYSDATE);
INSERT INTO ANSWER (ANSWER_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_ANSWER.NEXTVAL, 17,SYSDATE);

ROLLBACK;

SELECT *
FROM ANSWER;
-- 2.CHECK_ATTENDANCE(출석체크) / CHECK_ATTE_ID / P_MEMBER_ID / SUBMIT_DATE
--   평가지 제출과는 관계없이 결석자가 없으면 이 쿼리문은 실행되지 않는다.(P_MEMBER_ID 가 17인 사람은 결석자가 없음이라함.)
INSERT INTO CHECK_ATTENDANCE(CHECK_ATTE_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_CHECK_ATTENDANCE.NEXTVAL,1,SYSDATE);
INSERT INTO CHECK_ATTENDANCE(CHECK_ATTE_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_CHECK_ATTENDANCE.NEXTVAL,19,SYSDATE);
INSERT INTO CHECK_ATTENDANCE(CHECK_ATTE_ID , P_MEMBER_ID , SUBMIT_DATE)
VALUES(SEQ_CHECK_ATTENDANCE.NEXTVAL,15,SYSDATE);

SELECT *
FROM CHECK_ATTENDANCE;

ROLLBACK;

-- 3.ANSWER_ATTENDANCE(출석체크응답내용) / ANSWER_ATTENDANCE / CHECK_ATTE_ID / P_MEMBER_ID(결석지목받은 사람)
INSERT INTO ANSWER_ATTENDANCE(ANS_ATTE_ID , CHECK_ATTE_ID , P_MEMBER_ID)
VALUES(SEQ_ANSWER_ATTENDANCE.NEXTVAL,3,16);
INSERT INTO ANSWER_ATTENDANCE(ANS_ATTE_ID , CHECK_ATTE_ID , P_MEMBER_ID)
VALUES(SEQ_ANSWER_ATTENDANCE.NEXTVAL,3,18);

SELECT *
FROM ANSWER_ATTENDANCE;


-- 시퀀스 생성
CREATE SEQUENCE SEQ_ANSWER_DETAIL
NOCACHE;

--응답 테이블
SELECT *
FROM ANSWER;
--질문 테이블
SELECT *
FROM QUESTION;
/*
1	2	가장 친절한 사람은 누구인가요?	1
2	2	가장 불친절한 사람은 누구인가요?	-1
3	2	위험하게 라이딩한 사람은 누구인가요?	-1
4	1	GOOD	1
5	1	SOSO	0
6	1	BAD	-1
7	3	완주하지 못한 사람은 누구인가요?	-1
8	3	실제 난이도에 못 미친 사람은 누구인가요?	-1
*/
--응답한 참여자 조회
SELECT *
FROM PARTICIPATED_MEMBER PM JOIN ANSWER A
ON PM.P_MEMBER_ID = A.P_MEMBER_ID;

COMMIT;
-- 4.ANSWER_DETAIL(응답내용) / ANS_DETAIL_ID / ANSWER_ID / QUESTION_ID / P_MEMBER_ID
INSERT INTO ANSWER_DETAIL(ANS_DETAIL_ID , ANSWER_ID , QUESTION_ID , P_MEMBER_ID)
VALUES(SEQ_ANSWER_DETAIL.NEXTVAL, 5,1,1);
INSERT INTO ANSWER_DETAIL(ANS_DETAIL_ID , ANSWER_ID , QUESTION_ID , P_MEMBER_ID)
VALUES(SEQ_ANSWER_DETAIL.NEXTVAL, 8,1,17);
INSERT INTO ANSWER_DETAIL(ANS_DETAIL_ID , ANSWER_ID , QUESTION_ID , P_MEMBER_ID)
VALUES(SEQ_ANSWER_DETAIL.NEXTVAL, 8,3,1);

SELECT *
FROM ANSWER_DETAIL;

COMMIT;
----------------------------------------------------------------------------------
-- 1. 평가기간인 모임이 있는지 SELECT USER_ID = 2 일때
--    종료시간 후, 
SELECT END_DATE +7 AS EVADATE
FROM RIDING
WHERE RIDING_ID = (SELECT RIDING_ID
                   FROM PARTICIPATED_MEMBER 
                   WHERE USER_ID = 2
                   );
    
-- 2. 방장인지 아닌지 체크하는 SELECT  USER_ID = 2 일때
---   0 이면 방장 아닌거임.
SELECT COUNT(*) AS LEADERCOUNT
FROM RIDING
WHERE LEADER_ID = 2;

-- 7. 이미 제출했는지 확인하는 쿼리
SELECT COUNT(*) AS ANSWERCOUNT
FROM PARTICIPATED_MEMBER PM JOIN ANSWER A
ON PM.P_MEMBER_ID = A.P_MEMBER_ID
WHERE PM.USER_ID = 2;

COMMIT;