ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "CHECK_ATTENDANCE" ADD CONSTRAINT "PK_CHECK_ATTENDANCE" PRIMARY KEY (
	"CHECK_ATTE_ID"
);

ALTER TABLE "EVALUATE_TYPE" ADD CONSTRAINT "PK_EVALUATE_TYPE" PRIMARY KEY (
	"E_TYPE_ID"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "PK_PROFILE_IMG" PRIMARY KEY (
	"PIMG_ID"
);

ALTER TABLE "SPEED" ADD CONSTRAINT "PK_SPEED" PRIMARY KEY (
	"SPEED_ID"
);

ALTER TABLE "STEP" ADD CONSTRAINT "PK_STEP" PRIMARY KEY (
	"STEP_ID"
);

ALTER TABLE "EAT_PREFERENCE" ADD CONSTRAINT "PK_EAT_PREFERENCE" PRIMARY KEY (
	"EAT_P_ID"
);

ALTER TABLE "DINING_PREFERENCE" ADD CONSTRAINT "PK_DINING_PREFERENCE" PRIMARY KEY (
	"DINING_P_ID"
);

ALTER TABLE "MOOD_PREFERENCE" ADD CONSTRAINT "PK_MOOD_PREFERENCE" PRIMARY KEY (
	"MOOD_P_ID"
);

ALTER TABLE "WITHDRAW_USER" ADD CONSTRAINT "PK_WITHDRAW_USER" PRIMARY KEY (
	"WITHDRAW_ID"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"QUESTION_ID"
);

ALTER TABLE "MEMBER_ACCESS" ADD CONSTRAINT "PK_MEMBER_ACCESS" PRIMARY KEY (
	"ACCESS_ID"
);

ALTER TABLE "ANSWER" ADD CONSTRAINT "PK_ANSWER" PRIMARY KEY (
	"ANSWER_ID"
);

ALTER TABLE "FACILITY_TYPE" ADD CONSTRAINT "PK_FACILITY_TYPE" PRIMARY KEY (
	"F_TYPE_ID"
);

ALTER TABLE "SINGLE_RIDING" ADD CONSTRAINT "PK_SINGLE_RIDING" PRIMARY KEY (
	"S_RIDING_ID"
);

ALTER TABLE "RIDING" ADD CONSTRAINT "PK_RIDING" PRIMARY KEY (
	"RIDING_ID"
);

ALTER TABLE "ADD_FRIEND" ADD CONSTRAINT "PK_ADD_FRIEND" PRIMARY KEY (
	"ADD_FRIEND_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "NOTICE_CONTENT" ADD CONSTRAINT "PK_NOTICE_CONTENT" PRIMARY KEY (
	"N_CONTENT_ID"
);

ALTER TABLE "SINGLE_RIDING_RECORD" ADD CONSTRAINT "PK_SINGLE_RIDING_RECORD" PRIMARY KEY (
	"S_RECORD_ID"
);

ALTER TABLE "ANSWER_ATTENDANCE" ADD CONSTRAINT "PK_ANSWER_ATTENDANCE" PRIMARY KEY (
	"ANS_ATTE_ID"
);

ALTER TABLE "ANSWER_DETAIL" ADD CONSTRAINT "PK_ANSWER_DETAIL" PRIMARY KEY (
	"ANS_DETAIL_ID"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INQUIRY_ID"
);

ALTER TABLE "INQUIRY_PROCESS" ADD CONSTRAINT "PK_INQUIRY_PROCESS" PRIMARY KEY (
	"INQ_PROC_ID"
);

ALTER TABLE "SINGLE_RIDING_POINT" ADD CONSTRAINT "PK_SINGLE_RIDING_POINT" PRIMARY KEY (
	"S_POINT_ID"
);

ALTER TABLE "MESSAGE" ADD CONSTRAINT "PK_MESSAGE" PRIMARY KEY (
	"MESSAGE_ID"
);

ALTER TABLE "FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY (
	"FACILITY_ID"
);

ALTER TABLE "FACILITY_UPDATE_REQ" ADD CONSTRAINT "PK_FACILITY_UPDATE_REQ" PRIMARY KEY (
	"F_UPDATE_ID"
);

ALTER TABLE "REVIEW_REPORT" ADD CONSTRAINT "PK_REVIEW_REPORT" PRIMARY KEY (
	"REVIEW_R_ID"
);

ALTER TABLE "REVIEW_REPORT_PROCESS" ADD CONSTRAINT "PK_REVIEW_REPORT_PROCESS" PRIMARY KEY (
	"RR_PROC_ID"
);

ALTER TABLE "RESTAURANT" ADD CONSTRAINT "PK_RESTAURANT" PRIMARY KEY (
	"RESTAURANT_ID"
);

ALTER TABLE "RESTAURANT_DELETE_REQ" ADD CONSTRAINT "PK_RESTAURANT_DELETE_REQ" PRIMARY KEY (
	"R_DELETE_ID"
);

ALTER TABLE "RESTAURANT_UPDATE_REQ" ADD CONSTRAINT "PK_RESTAURANT_UPDATE_REQ" PRIMARY KEY (
	"R_UPDATE_ID"
);

ALTER TABLE "RESTAURANT_REVIEW" ADD CONSTRAINT "PK_RESTAURANT_REVIEW" PRIMARY KEY (
	"R_REVIEW_ID"
);

ALTER TABLE "PARTICIPATED_MEMBER" ADD CONSTRAINT "PK_PARTICIPATED_MEMBER" PRIMARY KEY (
	"P_MEMBER_ID"
);

ALTER TABLE "PENALTY_TYPE" ADD CONSTRAINT "PK_PENALTY_TYPE" PRIMARY KEY (
	"PENALTY_TYPE_ID"
);

ALTER TABLE "REVIEW_PENALTY" ADD CONSTRAINT "PK_REVIEW_PENALTY" PRIMARY KEY (
	"R_PENALTY_ID"
);

ALTER TABLE "INVITE" ADD CONSTRAINT "PK_INVITE" PRIMARY KEY (
	"INVITE_ID"
);

ALTER TABLE "RIDING_POINT" ADD CONSTRAINT "PK_RIDING_POINT" PRIMARY KEY (
	"POINT_ID"
);

ALTER TABLE "RIDING_RECORD" ADD CONSTRAINT "PK_RIDING_RECORD" PRIMARY KEY (
	"RECORD_ID"
);

ALTER TABLE "EVALUATION_GRADE" ADD CONSTRAINT "PK_EVALUATION_GRADE" PRIMARY KEY (
	"E_GRADE_ID"
);

ALTER TABLE "CONTRIBUTION_GRADE" ADD CONSTRAINT "PK_CONTRIBUTION_GRADE" PRIMARY KEY (
	"C_GRADE_ID"
);

ALTER TABLE "NICKNAME_CHANGE" ADD CONSTRAINT "PK_NICKNAME_CHANGE" PRIMARY KEY (
	"CHANGE_ID"
);

ALTER TABLE "PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY (
	"PROFILE_ID"
);

ALTER TABLE "EVALUATION_RECORD" ADD CONSTRAINT "PK_EVALUATION_RECORD" PRIMARY KEY (
	"EVA_RECORD_ID"
);

ALTER TABLE "REPORT_PROCESS_STATUS" ADD CONSTRAINT "PK_REPORT_PROCESS_STATUS" PRIMARY KEY (
	"REPORT_STATUS_ID"
);

ALTER TABLE "FACILITY_DELETE_REQ" ADD CONSTRAINT "PK_FACILITY_DELETE_REQ" PRIMARY KEY (
	"F_DELETE_ID"
);

ALTER TABLE "PARTICIPANT_REPORT" ADD CONSTRAINT "PK_PARTICIPANT_REPORT" PRIMARY KEY (
	"PARTICI_R_ID"
);

ALTER TABLE "PARTICIPANT_REPORT_PROCESS" ADD CONSTRAINT "PK_PARTICIPANT_REPORT_PROCESS" PRIMARY KEY (
	"PR_PROC_ID"
);

ALTER TABLE "PARTICIPANT_PENALTY" ADD CONSTRAINT "PK_PARTICIPANT_PENALTY" PRIMARY KEY (
	"P_PENALTY_ID"
);

ALTER TABLE "SEX_PREFERENCE" ADD CONSTRAINT "PK_SEX_PREFERENCE" PRIMARY KEY (
	"SEX_P_ID"
);

ALTER TABLE "AGE_PREFERENCE" ADD CONSTRAINT "PK_AGE_PREFERENCE" PRIMARY KEY (
	"AGE_P_ID"
);

ALTER TABLE "ANSWER_DETAIL_LEADERSHIP" ADD CONSTRAINT "PK_ANSWER_DETAIL_LEADERSHIP" PRIMARY KEY (
	"ANS_L_ID"
);

ALTER TABLE "DELETED_RIDING" ADD CONSTRAINT "PK_DELETED_RIDING" PRIMARY KEY (
	"DEL_RIDING_ID"
);

ALTER TABLE "ABSCOND" ADD CONSTRAINT "PK_ABSCOND" PRIMARY KEY (
	"ABSCOND_ID"
);

ALTER TABLE "INQUIRY_PROCESS_STATUS" ADD CONSTRAINT "PK_INQUIRY_PROCESS_STATUS" PRIMARY KEY (
	"INQUIRY_STATUS_ID"
);