CREATE TABLE "MEMBER" (
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"ACCESS_ID"	NUMBER(1)		NOT NULL,
	"JOIN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USER_ID" IS '회원ID참조는 이 테이블을 참조한다.';

COMMENT ON COLUMN "MEMBER"."ACCESS_ID" IS '0관리자 / 1회원';

COMMENT ON COLUMN "MEMBER"."JOIN_DATE" IS '가입한 날짜';

CREATE TABLE "CHECK_ATTENDANCE" (
	"CHECK_ATTE_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"SUBMIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "CHECK_ATTENDANCE"."CHECK_ATTE_ID" IS '어떤사람이 출석체크했다';

COMMENT ON COLUMN "CHECK_ATTENDANCE"."P_MEMBER_ID" IS '응답자 정보 + 모임 정보';

COMMENT ON COLUMN "CHECK_ATTENDANCE"."SUBMIT_DATE" IS '폼 제출일';

CREATE TABLE "EVALUATE_TYPE" (
	"E_TYPE_ID"	VARCHAR2(30)		NOT NULL,
	"E_TYPE_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "EVALUATE_TYPE"."E_TYPE_ID" IS '평가 점수 타입에 대한 범례';

COMMENT ON COLUMN "EVALUATE_TYPE"."E_TYPE_NAME" IS '매너/리더십/체력';

CREATE TABLE "PROFILE_IMG" (
	"PIMG_ID"	CHAR(1)		NOT NULL,
	"PI_ADDRESS"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "PROFILE_IMG"."PIMG_ID" IS '프로필 사진 저장하는 테이블 (범례)';

COMMENT ON COLUMN "PROFILE_IMG"."PI_ADDRESS" IS 'IMG 주소값';

CREATE TABLE "SPEED" (
	"SPEED_ID"	NUMBER(1)		NOT NULL,
	"SPPED_TYPE"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "SPEED"."SPEED_ID" IS '속도에 대한 범례';

COMMENT ON COLUMN "SPEED"."SPPED_TYPE" IS '0(제한없음)/1(20미만)/2(20~24)/3(24이상)';

CREATE TABLE "STEP" (
	"STEP_ID"	NUMBER(1)		NOT NULL,
	"STEP_TYPE"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "STEP"."STEP_ID" IS '숙련도에 대한 범례';

COMMENT ON COLUMN "STEP"."STEP_TYPE" IS '0(제한없음)/1(1년미만)/2(1~3년)/3(3~5년)/4(6년이상)';

CREATE TABLE "EAT_PREFERENCE" (
	"EAT_P_ID"	NUMBER(1)		NOT NULL,
	"EP_CONTENT"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "EAT_PREFERENCE"."EAT_P_ID" IS '식사선호도에 대한 범례';

COMMENT ON COLUMN "EAT_PREFERENCE"."EP_CONTENT" IS '0 상관없음 / 1 식사해요 / 2식사안해용';

CREATE TABLE "DINING_PREFERENCE" (
	"DINING_P_ID"	NUMBER(1)		NOT NULL,
	"DP_CONTENT"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "DINING_PREFERENCE"."DINING_P_ID" IS '회식선호도에 대한 범례';

COMMENT ON COLUMN "DINING_PREFERENCE"."DP_CONTENT" IS '0(제한없음)/1회식해요/2회식안해요';

CREATE TABLE "MOOD_PREFERENCE" (
	"MOOD_P_ID"	NUMBER(1)		NOT NULL,
	"MP_CONTENT"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "MOOD_PREFERENCE"."MOOD_P_ID" IS '분위기선호도에 대한 범례';

COMMENT ON COLUMN "MOOD_PREFERENCE"."MP_CONTENT" IS '0(제한없음)/1(침묵)/2(친목)';

CREATE TABLE "WITHDRAW_USER" (
	"WITHDRAW_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"WITHDRAW_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "WITHDRAW_USER"."WITHDRAW_ID" IS '탈퇴하면 INSERT되는 테이블/회원테이블에서 레코드가 삭제되는게 아님!';

COMMENT ON COLUMN "WITHDRAW_USER"."USER_ID" IS '탈퇴한 회원ID';

COMMENT ON COLUMN "WITHDRAW_USER"."WITHDRAW_DATE" IS '탈퇴한 날짜';

CREATE TABLE "QUESTION" (
	"QUESTION_ID"	VARCHAR2(30)		NOT NULL,
	"E_TYPE_ID"	VARCHAR2(30)		NOT NULL,
	"Q_CONTENT"	VARCHAR2(100)		NOT NULL,
	"POINT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "QUESTION"."QUESTION_ID" IS '평가문항 내용과 할당 점수 범례';

COMMENT ON COLUMN "QUESTION"."E_TYPE_ID" IS '매너/리더십/체력';

COMMENT ON COLUMN "QUESTION"."Q_CONTENT" IS '가장 친절한 사람은?';

COMMENT ON COLUMN "QUESTION"."POINT" IS '문항에 따른 점수';

CREATE TABLE "MEMBER_ACCESS" (
	"ACCESS_ID"	NUMBER(1)		NOT NULL,
	"ACCESS_TYPE"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_ACCESS"."ACCESS_ID" IS '회원 권한에 대한 범례';

COMMENT ON COLUMN "MEMBER_ACCESS"."ACCESS_TYPE" IS '1관리자 / 2 회원';

CREATE TABLE "ANSWER" (
	"ANSWER_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"SUBMIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "ANSWER"."ANSWER_ID" IS '모임참여한사람 중 평가에 응답한 사람';

COMMENT ON COLUMN "ANSWER"."P_MEMBER_ID" IS '응답자(참여자)정보+모임정보';

COMMENT ON COLUMN "ANSWER"."SUBMIT_DATE" IS '평가폼 제출일';

CREATE TABLE "FACILITY_TYPE" (
	"F_TYPE_ID"	NUMBER(1)		NOT NULL,
	"F_TYPE_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "FACILITY_TYPE"."F_TYPE_ID" IS '편의시설종류에 대한 범례';

COMMENT ON COLUMN "FACILITY_TYPE"."F_TYPE_NAME" IS '1. 화장실 2.음수대';

CREATE TABLE "SINGLE_RIDING" (
	"S_RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"LEADER_ID"	VARCHAR2(30)		NOT NULL,
	"RIDING_NAME"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"CREATED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"START_X"	VARCHAR2(500)		NOT NULL,
	"START_Y"	VARCHAR2(500)		NOT NULL,
	"START_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"START_DETAIL"	VARCHAR2(500)		NOT NULL,
	"END_X"	VARCHAR2(500)		NOT NULL,
	"END_Y"	VARCHAR2(500)		NOT NULL,
	"END_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"END_DETAIL"	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN "SINGLE_RIDING"."S_RIDING_ID" IS '1인모임라이딩';

COMMENT ON COLUMN "SINGLE_RIDING"."LEADER_ID" IS '1인모임개설자(회원)';

COMMENT ON COLUMN "SINGLE_RIDING"."RIDING_NAME" IS '모임이름';

COMMENT ON COLUMN "SINGLE_RIDING"."START_DATE" IS '라이딩출발날짜와 시간';

COMMENT ON COLUMN "SINGLE_RIDING"."END_DATE" IS '라이딩종료날짜와 시간';

COMMENT ON COLUMN "SINGLE_RIDING"."CREATED_DATE" IS '모임생성일';

COMMENT ON COLUMN "SINGLE_RIDING"."START_X" IS '라이딩 출발 장소 좌표 X';

COMMENT ON COLUMN "SINGLE_RIDING"."START_Y" IS '라이딩 출발 장소 좌표 Y';

COMMENT ON COLUMN "SINGLE_RIDING"."START_ADDRESS" IS '라이딩 출발 장소 주소 도로명과 지번';

COMMENT ON COLUMN "SINGLE_RIDING"."START_DETAIL" IS '라이딩 출발 장소 주소의 동호수, 건물';

COMMENT ON COLUMN "SINGLE_RIDING"."END_X" IS '라이딩 도착 장소 좌표 X';

COMMENT ON COLUMN "SINGLE_RIDING"."END_Y" IS '라이딩 도착 장소 좌표 Y';

COMMENT ON COLUMN "SINGLE_RIDING"."END_ADDRESS" IS '라이딩 도착 장소 주소 도로명과 지번';

COMMENT ON COLUMN "SINGLE_RIDING"."END_DETAIL" IS '라이딩 도착 장소 주소 동호수, 건물';

CREATE TABLE "RIDING" (
	"RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"LEADER_ID"	VARCHAR2(30)		NOT NULL,
	"STEP_ID"	NUMBER(1)		NOT NULL,
	"SPEED_ID"	NUMBER(1)		NOT NULL,
	"MOOD_P_ID"	NUMBER(1)		NOT NULL,
	"DINING_P_ID"	NUMBER(1)		NOT NULL,
	"EAT_P_ID"	NUMBER(1)		NOT NULL,
	"AGE_P_ID"	CHAR(1)		NOT NULL,
	"SEX_P_ID"	CHAR(1)		NOT NULL,
	"E_GRADE_ID"	NUMBER(1)		NOT NULL,
	"RIDING_NAME"	VARCHAR2(300)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"CREATED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MAXIMUM"	NUMBER(1)		NOT NULL,
	"MEET_X"	VARCHAR2(500)		NOT NULL,
	"MEET_Y"	VARCHAR2(500)		NOT NULL,
	"MEET_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"MEET_DETAIL"	VARCHAR2(500)		NOT NULL,
	"START_X"	VARCHAR2(500)		NOT NULL,
	"START_Y"	VARCHAR2(500)		NOT NULL,
	"START_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"START_DETAIL"	VARCHAR2(500)		NOT NULL,
	"END_X"	VARCHAR2(500)		NOT NULL,
	"END_Y"	VARCHAR2(500)		NOT NULL,
	"END_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"CONFIRM_DATE"	DATE		NULL
);

COMMENT ON COLUMN "RIDING"."RIDING_ID" IS '다인 모임 라이딩';

COMMENT ON COLUMN "RIDING"."LEADER_ID" IS '방을 생성한 회원ID';

COMMENT ON COLUMN "RIDING"."STEP_ID" IS '방을 나타내는 숙련도 범례';

COMMENT ON COLUMN "RIDING"."SPEED_ID" IS '방을 나타내는 속도 범례';

COMMENT ON COLUMN "RIDING"."MOOD_P_ID" IS '방을 나타내는 분위기 범례';

COMMENT ON COLUMN "RIDING"."DINING_P_ID" IS '방을 나타내는 회식 범례';

COMMENT ON COLUMN "RIDING"."EAT_P_ID" IS '방을 나타내는 식사 범례';

COMMENT ON COLUMN "RIDING"."AGE_P_ID" IS '방을 나타내는 연령 제한 범례';

COMMENT ON COLUMN "RIDING"."SEX_P_ID" IS '방을 나타내는 성별 제한 범례';

COMMENT ON COLUMN "RIDING"."E_GRADE_ID" IS '여기가 만약 3이면  3,4,5 만 참여 가능 / 선택 가능한건 방장 등급3이면 여기에 적을 수 있는건 1,2,3이다.';

COMMENT ON COLUMN "RIDING"."RIDING_NAME" IS '모임이름';

COMMENT ON COLUMN "RIDING"."START_DATE" IS '모임 시작 장소에 모이는 날짜랑 시간';

COMMENT ON COLUMN "RIDING"."END_DATE" IS '라이딩 종료 날짜랑 시간';

COMMENT ON COLUMN "RIDING"."CREATED_DATE" IS '모임을 생성한 날짜 테이블에 INSERT때';

COMMENT ON COLUMN "RIDING"."MAXIMUM" IS '최대인원수 2~9명';

COMMENT ON COLUMN "RIDING"."MEET_X" IS '모임 시작 장소 좌표 x';

COMMENT ON COLUMN "RIDING"."MEET_Y" IS '모임 시작 장소 좌표 y';

COMMENT ON COLUMN "RIDING"."MEET_ADDRESS" IS '모임 시작 장소 도로명 / 지번';

COMMENT ON COLUMN "RIDING"."MEET_DETAIL" IS '모임 시작 장소 동호수,건물';

COMMENT ON COLUMN "RIDING"."START_X" IS '라이딩 출발 장소 좌표 x';

COMMENT ON COLUMN "RIDING"."START_Y" IS '라이딩 출발 장소 좌표 y';

COMMENT ON COLUMN "RIDING"."START_ADDRESS" IS '라이딩 출발 장소 도로명 / 지번';

COMMENT ON COLUMN "RIDING"."START_DETAIL" IS '라이딩 출발 장소 동호수, 건물';

COMMENT ON COLUMN "RIDING"."END_X" IS '라이딩 도착 장소 좌표 x';

COMMENT ON COLUMN "RIDING"."END_Y" IS '라이딩 도착 장소 좌표 y';

COMMENT ON COLUMN "RIDING"."END_ADDRESS" IS '라이딩 도착 장소 도로명  / 지번';

COMMENT ON COLUMN "RIDING"."DETAIL_ADDRESS" IS '라이딩 도착 장소 동호수, 건물';

COMMENT ON COLUMN "RIDING"."CONFIRM_DATE" IS '방장이 모임을 확정하는 날짜';

CREATE TABLE "ADD_FRIEND" (
	"ADD_FRIEND_ID"	VARCHAR2(30)		NOT NULL,
	"SENDER_ID"	VARCHAR2(30)		NOT NULL,
	"RECEIVER_ID"	VARCHAR2(30)		NOT NULL,
	"ADD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL,
	"ACCEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "ADD_FRIEND"."ADD_FRIEND_ID" IS '친구신청에 대한 테이블';

COMMENT ON COLUMN "ADD_FRIEND"."SENDER_ID" IS '친구신청한 사람';

COMMENT ON COLUMN "ADD_FRIEND"."RECEIVER_ID" IS '친구신청 받은 사람 (한명이 끊으면 친구신청에서 DEL)';

COMMENT ON COLUMN "ADD_FRIEND"."ADD_DATE" IS '친구 신청한 날짜';

COMMENT ON COLUMN "ADD_FRIEND"."OPEN_DATE" IS '확인일 있고 수락일 없으면 성립 안 됨';

COMMENT ON COLUMN "ADD_FRIEND"."ACCEPT_DATE" IS '수락일 있으면 친구 관계 성립';

CREATE TABLE "NOTICE" (
	"NOTICE_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"N_CONTENT_ID"	NUMBER(1)		NOT NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '알림 테이블';

COMMENT ON COLUMN "NOTICE"."USER_ID" IS '알림 받은 회원';

COMMENT ON COLUMN "NOTICE"."N_CONTENT_ID" IS '알림상세내용에 대한 범례';

COMMENT ON COLUMN "NOTICE"."SEND_DATE" IS '알림INSERT 된 날짜';

COMMENT ON COLUMN "NOTICE"."OPEN_DATE" IS '열람하면 날짜 UPDATE';

CREATE TABLE "NOTICE_CONTENT" (
	"N_CONTENT_ID"	NUMBER(1)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL
);

COMMENT ON COLUMN "NOTICE_CONTENT"."N_CONTENT_ID" IS '알림상세내용에 대한 범례';

COMMENT ON COLUMN "NOTICE_CONTENT"."CONTENT" IS '1.모임이 확정 2.모임이 수정 3. 모임이 삭제  등등';

CREATE TABLE "SINGLE_RIDING_RECORD" (
	"S_RECORD_ID"	VARCHAR2(30)		NOT NULL,
	"S_RIDING_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "SINGLE_RIDING_RECORD"."S_RECORD_ID" IS '1인모임기록';

COMMENT ON COLUMN "SINGLE_RIDING_RECORD"."S_RIDING_ID" IS '모임ID';

CREATE TABLE "ANSWER_ATTENDANCE" (
	"ANS_ATTE_ID"	VARCHAR2(30)		NOT NULL,
	"CHECK_ATTE_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ANSWER_ATTENDANCE"."ANS_ATTE_ID" IS '어떤 사람이 누구를 결석체크';

COMMENT ON COLUMN "ANSWER_ATTENDANCE"."CHECK_ATTE_ID" IS '누가 출석체크 제출';

COMMENT ON COLUMN "ANSWER_ATTENDANCE"."P_MEMBER_ID" IS '결석한 사람';

CREATE TABLE "ANSWER_DETAIL" (
	"ANS_DETAIL_ID"	VARCHAR2(30)		NOT NULL,
	"ANSWER_ID"	VARCHAR2(30)		NOT NULL,
	"QUESTION_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ANSWER_DETAIL"."ANS_DETAIL_ID" IS '응답한사람이 어떤 문항에 어떤 대답';

COMMENT ON COLUMN "ANSWER_DETAIL"."ANSWER_ID" IS '응답한사람';

COMMENT ON COLUMN "ANSWER_DETAIL"."QUESTION_ID" IS '문항 하나씩';

COMMENT ON COLUMN "ANSWER_DETAIL"."P_MEMBER_ID" IS '지목받은사람ID';

CREATE TABLE "INQUIRY" (
	"INQUIRY_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"INQUIRY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_ID" IS '회원이 문의 요청';

COMMENT ON COLUMN "INQUIRY"."USER_ID" IS '문의보내는사람';

COMMENT ON COLUMN "INQUIRY"."TITLE" IS '문의 제목';

COMMENT ON COLUMN "INQUIRY"."CONTENT" IS '문의 내용';

COMMENT ON COLUMN "INQUIRY"."INQUIRY_DATE" IS '문의 보낸 날짜';

CREATE TABLE "INQUIRY_PROCESS" (
	"INQ_PROC_ID"	VARCHAR2(30)		NOT NULL,
	"INQUIRY_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"INQUIRY_STATUS_ID"	NUMBER(1)		NOT NULL,
	"PROCESS_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "INQUIRY_PROCESS"."INQ_PROC_ID" IS '관리자가 문의 처리한 내역';

COMMENT ON COLUMN "INQUIRY_PROCESS"."INQUIRY_ID" IS '회원의 문의 요청';

COMMENT ON COLUMN "INQUIRY_PROCESS"."USER_ID" IS '문의처리자(관리자만 가능)';

COMMENT ON COLUMN "INQUIRY_PROCESS"."INQUIRY_STATUS_ID" IS '1.해결 2.반려';

COMMENT ON COLUMN "INQUIRY_PROCESS"."PROCESS_DATE" IS '문의 처리한 날짜';

CREATE TABLE "SINGLE_RIDING_POINT" (
	"S_POINT_ID"	VARCHAR2(30)		NOT NULL,
	"S_RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."S_POINT_ID" IS '경유지ID';

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."S_RIDING_ID" IS '한 모임당 경유지 최대 5개';

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."COORD_X" IS '경유지 좌표 X';

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."COORD_Y" IS '경유지 좌표 Y';

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."ADDRESS" IS '경유지 도로명 / 지번';

COMMENT ON COLUMN "SINGLE_RIDING_POINT"."DETAIL_ADDRESS" IS '경유지 동호수 , 건물';

CREATE TABLE "MESSAGE" (
	"MESSAGE_ID"	VARCHAR2(30)		NOT NULL,
	"SENDER_ID"	VARCHAR2(30)		NOT NULL,
	"RECEIVER_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"SEND_DATE"	DATE		NOT NULL,
	"RECEIVE_DATE"	DATE		NULL,
	"SEND_DEL_DATE"	DATE		NULL,
	"RCEI_DEL_DATE"	DATE		NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_ID" IS '테이블 시퀀스';

COMMENT ON COLUMN "MESSAGE"."SENDER_ID" IS '쪽지 받은 회원';

COMMENT ON COLUMN "MESSAGE"."RECEIVER_ID" IS '쪽지 보낸 회원';

COMMENT ON COLUMN "MESSAGE"."CONTENT" IS '쪽지 내용';

COMMENT ON COLUMN "MESSAGE"."SEND_DATE" IS '쪽지 보낸 날짜';

COMMENT ON COLUMN "MESSAGE"."RECEIVE_DATE" IS '쪽지 읽은 날짜';

COMMENT ON COLUMN "MESSAGE"."SEND_DEL_DATE" IS '발신자가 보낸 쪽지 삭제날짜';

COMMENT ON COLUMN "MESSAGE"."RCEI_DEL_DATE" IS '수신자가 받은 쪽지 삭제 날짜';

CREATE TABLE "FACILITY" (
	"FACILITY_ID"	VARCHAR2(30)		NOT NULL,
	"F_TYPE_ID"	NUMBER(1)		NOT NULL,
	"REQ_USER_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL,
	"ACEEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "FACILITY"."FACILITY_ID" IS '시설 등록 요청';

COMMENT ON COLUMN "FACILITY"."F_TYPE_ID" IS '편의시설종류에 대한 범례';

COMMENT ON COLUMN "FACILITY"."REQ_USER_ID" IS '등록요청자(회원)';

COMMENT ON COLUMN "FACILITY"."ADMIN_ID" IS '승인한 관리자';

COMMENT ON COLUMN "FACILITY"."COORD_X" IS '좌표X';

COMMENT ON COLUMN "FACILITY"."COORD_Y" IS '좌표Y';

COMMENT ON COLUMN "FACILITY"."ADDRESS" IS '도로명 / 지번';

COMMENT ON COLUMN "FACILITY"."DETAIL_ADDRESS" IS '동호수,건물';

COMMENT ON COLUMN "FACILITY"."REQUEST_DATE" IS '회원이 시설 등록 요청한 날짜';

COMMENT ON COLUMN "FACILITY"."OPEN_DATE" IS '관리자가 확인한 날짜(NULL이면 확인X)';

COMMENT ON COLUMN "FACILITY"."ACEEPT_DATE" IS '관리자가 승인한 날짜(승인 되면 시설 지도에 등록)';

CREATE TABLE "FACILITY_UPDATE_REQ" (
	"F_UPDATE_ID"	VARCHAR2(30)		NOT NULL,
	"FACILITY_ID"	VARCHAR2(30)		NOT NULL,
	"REQ_USER_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL,
	"ACCEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."F_UPDATE_ID" IS '테이블 시퀀스 ID';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."FACILITY_ID" IS '시설 등록 요청';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."REQ_USER_ID" IS '수정요청자(회원)';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."ADMIN_ID" IS '승인한관리자';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."COORD_X" IS '지도X';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."COORD_Y" IS '지도Y';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."ADDRESS" IS '도로명 / 지번';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."DETAIL_ADDRESS" IS '동호수 , 건물';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."CONTENT" IS '회원이 수정요청할때 적는 내용';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."REQUEST_DATE" IS '회원이 수정을 요청한 날짜';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."OPEN_DATE" IS '관리자가 열람하면 UPDATE';

COMMENT ON COLUMN "FACILITY_UPDATE_REQ"."ACCEPT_DATE" IS '확인일, 승인일 있으면 승인';

CREATE TABLE "REVIEW_REPORT" (
	"REVIEW_R_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"R_REVIEW_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "REVIEW_REPORT"."REVIEW_R_ID" IS '맛집 후기에 대한 신고요청';

COMMENT ON COLUMN "REVIEW_REPORT"."USER_ID" IS '신고한 회원ID';

COMMENT ON COLUMN "REVIEW_REPORT"."R_REVIEW_ID" IS '신고받은 게시글ID';

COMMENT ON COLUMN "REVIEW_REPORT"."CONTENT" IS '신고자가 입력하는 내용';

COMMENT ON COLUMN "REVIEW_REPORT"."REPORT_DATE" IS '신고요청일';

CREATE TABLE "REVIEW_REPORT_PROCESS" (
	"RR_PROC_ID"	VARCHAR2(30)		NOT NULL,
	"REVIEW_R_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"PROC_STATUS_ID"	NUMBER(1)		NOT NULL,
	"PROCESS_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "REVIEW_REPORT_PROCESS"."RR_PROC_ID" IS '맛집후기에 대한 신고를 관리자가 처리한 내역';

COMMENT ON COLUMN "REVIEW_REPORT_PROCESS"."REVIEW_R_ID" IS '맛집후기에 대한 신고요청ID';

COMMENT ON COLUMN "REVIEW_REPORT_PROCESS"."ADMIN_ID" IS '신고처리자(관리자만 가능)';

COMMENT ON COLUMN "REVIEW_REPORT_PROCESS"."PROC_STATUS_ID" IS '1.승인_패널티부여 2.승인_허위신고 3.반려';

COMMENT ON COLUMN "REVIEW_REPORT_PROCESS"."PROCESS_DATE" IS '처리일은 패널티시작일이다';

CREATE TABLE "RESTAURANT" (
	"RESTAURANT_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"RESTA_NAME"	VARCHAR2(100)		NOT NULL,
	"REGISTER_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "RESTAURANT"."RESTAURANT_ID" IS '맛집 하나에 대한 테이블';

COMMENT ON COLUMN "RESTAURANT"."USER_ID" IS '맛집등록자(회원)';

COMMENT ON COLUMN "RESTAURANT"."COORD_X" IS '지도X';

COMMENT ON COLUMN "RESTAURANT"."COORD_Y" IS '지도Y';

COMMENT ON COLUMN "RESTAURANT"."RESTA_NAME" IS '맛집이름(홍대순대국처럼)';

COMMENT ON COLUMN "RESTAURANT"."REGISTER_DATE" IS '맛집 등록한 날짜';

COMMENT ON COLUMN "RESTAURANT"."ADDRESS" IS '도로명 / 지번';

COMMENT ON COLUMN "RESTAURANT"."DETAIL_ADDRESS" IS '동호수, 건물';

CREATE TABLE "RESTAURANT_DELETE_REQ" (
	"R_DELETE_ID"	VARCHAR2(30)		NOT NULL,
	"RESTAURANT_ID"	VARCHAR2(30)		NOT NULL,
	"REQ_USER_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NOT NULL,
	"ACCEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."R_DELETE_ID" IS '회원이 맛집에 대한 삭제를 요청';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."RESTAURANT_ID" IS '삭제가 필요한 맛집ID';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."REQ_USER_ID" IS '삭제요청자';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."ADMIN_ID" IS '맛집삭제승인자(관리자)';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."CONTENT" IS '삭제요청할때 회원이 적는 내용';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."REQUEST_DATE" IS '삭제요청할때 INSERT되는 날짜';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."OPEN_DATE" IS '관리자가 해당 요청을 확인한 날짜(NULL가능)';

COMMENT ON COLUMN "RESTAURANT_DELETE_REQ"."ACCEPT_DATE" IS '관리자가 해당 맛집을 삭제하면 UPDATE된다.';

CREATE TABLE "RESTAURANT_UPDATE_REQ" (
	"R_UPDATE_ID"	VARCHAR2(30)		NOT NULL,
	"RESTAURANT_ID"	VARCHAR2(30)		NOT NULL,
	"REQ_USER_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"RESTA_NAME"	VARCHAR2(100)		NOT NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL,
	"ACCEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."R_UPDATE_ID" IS '회원이 맛집 수정을 요청할 때';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."RESTAURANT_ID" IS '수정이 필요한 맛집 ID';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."REQ_USER_ID" IS '수정요청자';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."ADMIN_ID" IS '맛집수정승인자(관리자)';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."RESTA_NAME" IS '맛집 이름';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."COORD_X" IS '지도 좌표 X';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."COORD_Y" IS '지도 좌표Y';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."ADDRESS" IS '도로명 / 지번';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."DETAIL_ADDRESS" IS '동호수';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."CONTENT" IS '수정요청할때 회원이 적는 내용';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."REQUEST_DATE" IS '회원이 수정요청할 때 날짜';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."OPEN_DATE" IS '관리자가 해당 요청을 확인한 날짜(NULL 값이면 확인 안한거)';

COMMENT ON COLUMN "RESTAURANT_UPDATE_REQ"."ACCEPT_DATE" IS '관리자가 해당 요청을 승인한 날짜(날짜가 기입되면 맛집은 수정된다)';

CREATE TABLE "RESTAURANT_REVIEW" (
	"R_REVIEW_ID"	VARCHAR2(30)		NOT NULL,
	"RESTAURANT_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"CREATED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"VIEWS"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "RESTAURANT_REVIEW"."R_REVIEW_ID" IS '맛집 후기 게시글';

COMMENT ON COLUMN "RESTAURANT_REVIEW"."RESTAURANT_ID" IS '게시글이 참조하는 맛집 ID';

COMMENT ON COLUMN "RESTAURANT_REVIEW"."USER_ID" IS '맛집후기작성자';

COMMENT ON COLUMN "RESTAURANT_REVIEW"."CONTENT" IS '후기 내용';

COMMENT ON COLUMN "RESTAURANT_REVIEW"."CREATED_DATE" IS '작성한 날짜';

COMMENT ON COLUMN "RESTAURANT_REVIEW"."VIEWS" IS '조회수';

CREATE TABLE "PARTICIPATED_MEMBER" (
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"PARTICI_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "PARTICIPATED_MEMBER"."P_MEMBER_ID" IS '모임에 참여한 참여자들 하나하나(방장 포함)';

COMMENT ON COLUMN "PARTICIPATED_MEMBER"."USER_ID" IS '라이딩 참여자';

COMMENT ON COLUMN "PARTICIPATED_MEMBER"."RIDING_ID" IS '참여자가 참여한 모임 ID';

COMMENT ON COLUMN "PARTICIPATED_MEMBER"."PARTICI_DATE" IS '확정일전까지는 DEL / 모임속성변경 신청일 NULL로 U0PDATE';

CREATE TABLE "PENALTY_TYPE" (
	"PENALTY_TYPE_ID"	NUMBER(1)		NOT NULL,
	"CONTENT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "PENALTY_TYPE"."PENALTY_TYPE_ID" IS '패널티종류에 대한 범례';

COMMENT ON COLUMN "PENALTY_TYPE"."CONTENT" IS '1.사이트이용제한 / 2.모임생성 및 참여제한';

CREATE TABLE "REVIEW_PENALTY" (
	"R_PENALTY_ID"	VARCHAR2(30)		NOT NULL,
	"PENALTY_TYPE_ID"	NUMBER(1)		NOT NULL,
	"RR_PROC_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "REVIEW_PENALTY"."PENALTY_TYPE_ID" IS '1.사이트이용제한 / 2.모임생성 및 참여제한';

COMMENT ON COLUMN "REVIEW_PENALTY"."RR_PROC_ID" IS '맛집후기에 대한 신고를 관리자가 처리한 내역';

CREATE TABLE "INVITE" (
	"INVITE_ID"	VARCHAR2(30)		NOT NULL,
	"SENDER_ID"	VARCHAR2(30)		NOT NULL,
	"RECEIVER_ID"	VARCHAR2(30)		NOT NULL,
	"RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"SEND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "INVITE"."INVITE_ID" IS '모임 초대에 대한 테이블';

COMMENT ON COLUMN "INVITE"."SENDER_ID" IS '모임 초대를 한 사람';

COMMENT ON COLUMN "INVITE"."RECEIVER_ID" IS '모임 초대를 받은 사람';

COMMENT ON COLUMN "INVITE"."RIDING_ID" IS '초대한 모임';

COMMENT ON COLUMN "INVITE"."SEND_DATE" IS '초대한 날짜';

CREATE TABLE "RIDING_POINT" (
	"POINT_ID"	VARCHAR2(30)		NOT NULL,
	"RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"COORD_X"	VARCHAR2(500)		NOT NULL,
	"COORD_Y"	VARCHAR2(500)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL
);

COMMENT ON COLUMN "RIDING_POINT"."POINT_ID" IS '같은 모임에 대한 경유지는 5개';

COMMENT ON COLUMN "RIDING_POINT"."RIDING_ID" IS '경유지를 포함하는 모임 ID';

COMMENT ON COLUMN "RIDING_POINT"."COORD_X" IS '경유지 좌표 X';

COMMENT ON COLUMN "RIDING_POINT"."COORD_Y" IS '경유지 좌표 Y';

COMMENT ON COLUMN "RIDING_POINT"."ADDRESS" IS '경유지 도로명 / 지번';

COMMENT ON COLUMN "RIDING_POINT"."DETAIL_ADDRESS" IS '경유지 동호수, 건물';

CREATE TABLE "RIDING_RECORD" (
	"RECORD_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "RIDING_RECORD"."RECORD_ID" IS '다인모임기록';

COMMENT ON COLUMN "RIDING_RECORD"."P_MEMBER_ID" IS '참여자 + 모임 정보';

CREATE TABLE "EVALUATION_GRADE" (
	"E_GRADE_ID"	NUMBER(1)		NOT NULL,
	"GRADE_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "EVALUATION_GRADE"."E_GRADE_ID" IS '평가 점수 등급에 대한 범례';

COMMENT ON COLUMN "EVALUATION_GRADE"."GRADE_NAME" IS '1~5등급, 00자전거';

CREATE TABLE "CONTRIBUTION_GRADE" (
	"C_GRADE_ID"	NUMBER(1)		NOT NULL,
	"GRADE_NAME"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "CONTRIBUTION_GRADE"."C_GRADE_ID" IS '공헌도 점수 등급에 대한 범례';

COMMENT ON COLUMN "CONTRIBUTION_GRADE"."GRADE_NAME" IS '1~4등급, 00헬멧';

CREATE TABLE "NICKNAME_CHANGE" (
	"CHANGE_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"CHANGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "NICKNAME_CHANGE"."CHANGE_ID" IS '회원이 닉네임을 변경했다';

COMMENT ON COLUMN "NICKNAME_CHANGE"."USER_ID" IS '닉네임변경한 사람ID';

COMMENT ON COLUMN "NICKNAME_CHANGE"."CHANGE_DATE" IS '닉네임 변경한 날짜';

CREATE TABLE "PROFILE" (
	"PROFILE_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"MOOD_P_ID"	NUMBER(1)		NOT NULL,
	"EAT_P_ID"	NUMBER(1)		NOT NULL,
	"PIMG_ID"	CHAR(1)		NOT NULL,
	"DINING_P_ID"	NUMBER(1)		NOT NULL,
	"SEX_P_ID"	CHAR(1)		NOT NULL,
	"AGE_P_ID"	CHAR(1)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"BIRTHDAY"	DATE		NOT NULL,
	"SEX"	CHAR(1)		NOT NULL,
	"PASSWORD"	VARCHAR2(30)		NOT NULL,
	"NICKNAME"	VARCHAR2(50)		NOT NULL,
	"INTRODUCE"	VARCHAR2(400)		NULL
);

COMMENT ON COLUMN "PROFILE"."PROFILE_ID" IS '개인정보ID';

COMMENT ON COLUMN "PROFILE"."USER_ID" IS '회원참조는 회원생성테이블을 참조함';

COMMENT ON COLUMN "PROFILE"."MOOD_P_ID" IS '0제한없음/1침묵/2친목';

COMMENT ON COLUMN "PROFILE"."EAT_P_ID" IS '0상관없음/1식사해요/2식사안해요';

COMMENT ON COLUMN "PROFILE"."PIMG_ID" IS '프로필 사진 IMG 주소';

COMMENT ON COLUMN "PROFILE"."DINING_P_ID" IS '0 제한없음 / 1회식해요 / 2회식안해요';

COMMENT ON COLUMN "PROFILE"."SEX_P_ID" IS 'T / F';

COMMENT ON COLUMN "PROFILE"."AGE_P_ID" IS 'T /F';

COMMENT ON COLUMN "PROFILE"."EMAIL" IS '@';

COMMENT ON COLUMN "PROFILE"."BIRTHDAY" IS '1998-06-06';

COMMENT ON COLUMN "PROFILE"."SEX" IS 'M 남자 / F 여자';

COMMENT ON COLUMN "PROFILE"."PASSWORD" IS '비번';

COMMENT ON COLUMN "PROFILE"."NICKNAME" IS '금지어 지정해둠';

COMMENT ON COLUMN "PROFILE"."INTRODUCE" IS '회원한줄소개';

CREATE TABLE "EVALUATION_RECORD" (
	"EVA_RECORD_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"ATTENDANCE"	VARCHAR2(20)		NOT NULL,
	"MANNER_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"LEADER_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"STAMINA_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"DIFFICULTY_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "EVALUATION_RECORD"."EVA_RECORD_ID" IS '모임 종료시간 +7일 후, 모든 참여자에 대한 평가기록';

COMMENT ON COLUMN "EVALUATION_RECORD"."P_MEMBER_ID" IS '모임의 모든 참여자들';

COMMENT ON COLUMN "EVALUATION_RECORD"."ATTENDANCE" IS '7일간 평가 후,출석 / 결석';

COMMENT ON COLUMN "EVALUATION_RECORD"."MANNER_SCORE" IS '7일간 받은 점수 총합';

COMMENT ON COLUMN "EVALUATION_RECORD"."LEADER_SCORE" IS '7일간 받은 점수 총합';

COMMENT ON COLUMN "EVALUATION_RECORD"."STAMINA_SCORE" IS '7일간 받은 점수 총합';

COMMENT ON COLUMN "EVALUATION_RECORD"."DIFFICULTY_SCORE" IS '7일간 받은 점수 통합';

COMMENT ON COLUMN "EVALUATION_RECORD"."INSERT_DATE" IS '누군가 라이딩조회할때 INSERT';

CREATE TABLE "REPORT_PROCESS_STATUS" (
	"REPORT_STATUS_ID"	NUMBER(1)		NOT NULL,
	"CONTENT"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "REPORT_PROCESS_STATUS"."REPORT_STATUS_ID" IS '신고처리에 대한 분류 범례';

COMMENT ON COLUMN "REPORT_PROCESS_STATUS"."CONTENT" IS '1.승인_패널티처리 / 2.승인-허위신고 / 3. 반려';

CREATE TABLE "FACILITY_DELETE_REQ" (
	"F_DELETE_ID"	VARCHAR2(30)		NOT NULL,
	"FACILITY_ID"	VARCHAR2(30)		NOT NULL,
	"REQ_USER_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REQUEST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_DATE"	DATE		NULL,
	"ACCEPT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."F_DELETE_ID" IS '회원이 시설삭제 요청';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."FACILITY_ID" IS '등록된 시설';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."REQ_USER_ID" IS '삭제요청자(회원)';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."ADMIN_ID" IS '승인한 관리자';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."CONTENT" IS '회원이 삭제 요청할 때 적는 내용';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."REQUEST_DATE" IS '회원이 삭제 요청한 날짜';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."OPEN_DATE" IS '관리자가 확인한 날짜';

COMMENT ON COLUMN "FACILITY_DELETE_REQ"."ACCEPT_DATE" IS '관리자가 승인한 날짜(여기 값있으면 시설은 삭제된거)';

CREATE TABLE "PARTICIPANT_REPORT" (
	"PARTICI_R_ID"	VARCHAR2(30)		NOT NULL,
	"USER_ID"	VARCHAR2(30)		NOT NULL,
	"REPORTED_ID"	VARCHAR2(30)		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "PARTICIPANT_REPORT"."PARTICI_R_ID" IS '모임평가에서 참여자 신고';

COMMENT ON COLUMN "PARTICIPANT_REPORT"."USER_ID" IS '신고한 회원ID';

COMMENT ON COLUMN "PARTICIPANT_REPORT"."REPORTED_ID" IS '신고받은 회원ID';

COMMENT ON COLUMN "PARTICIPANT_REPORT"."CONTENT" IS '신고자가 작성하는 내용';

COMMENT ON COLUMN "PARTICIPANT_REPORT"."REPORT_DATE" IS '신고요청날짜';

CREATE TABLE "PARTICIPANT_REPORT_PROCESS" (
	"PR_PROC_ID"	VARCHAR2(30)		NOT NULL,
	"PARTICI_R_ID"	VARCHAR2(30)		NOT NULL,
	"ADMIN_ID"	VARCHAR2(30)		NOT NULL,
	"PROC_STATUS_ID"	NUMBER(1)		NOT NULL,
	"PROCESS_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "PARTICIPANT_REPORT_PROCESS"."PR_PROC_ID" IS '관리자가 모임참여자신고 처리 내역';

COMMENT ON COLUMN "PARTICIPANT_REPORT_PROCESS"."PARTICI_R_ID" IS '모임평가에서 참여자 신고';

COMMENT ON COLUMN "PARTICIPANT_REPORT_PROCESS"."ADMIN_ID" IS '신고처리자(관리자만 가능)';

COMMENT ON COLUMN "PARTICIPANT_REPORT_PROCESS"."PROC_STATUS_ID" IS '1.승인 2.허위신고 3.반려';

COMMENT ON COLUMN "PARTICIPANT_REPORT_PROCESS"."PROCESS_DATE" IS '신고를 처리한 날짜 , 패널티 시작일과 같다';

CREATE TABLE "PARTICIPANT_PENALTY" (
	"P_PENALTY_ID"	VARCHAR2(30)		NOT NULL,
	"PENALTY_TYPE_ID"	NUMBER(1)		NOT NULL,
	"PR_PROC_ID"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "PARTICIPANT_PENALTY"."P_PENALTY_ID" IS '모임참여자에 대한 패널티부여 내역';

COMMENT ON COLUMN "PARTICIPANT_PENALTY"."PENALTY_TYPE_ID" IS '1.사이트이용제한/2.모임생성및 참여제한';

COMMENT ON COLUMN "PARTICIPANT_PENALTY"."PR_PROC_ID" IS '관리자가 모임참여자신고 처리 내역';

CREATE TABLE "SEX_PREFERENCE" (
	"SEX_P_ID"	CHAR(1)		NOT NULL,
	"SP_CONTENT"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "SEX_PREFERENCE"."SEX_P_ID" IS '성별제한선호에 대한 범례';

COMMENT ON COLUMN "SEX_PREFERENCE"."SP_CONTENT" IS 'T 제한선호함 / F 제한선호안함';

CREATE TABLE "AGE_PREFERENCE" (
	"AGE_P_ID"	CHAR(1)		NOT NULL,
	"AP_CONTENT"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "AGE_PREFERENCE"."AGE_P_ID" IS '연령제한선호에 대한 범례';

COMMENT ON COLUMN "AGE_PREFERENCE"."AP_CONTENT" IS 'T 제한선호함 / F제한선호안함';

CREATE TABLE "ANSWER_DETAIL_LEADERSHIP" (
	"ANS_L_ID"	VARCHAR2(30)		NOT NULL,
	"ANSWER_ID"	VARCHAR2(30)		NOT NULL,
	"QUESTION_ID"	VARCHAR2(30)		NOT NULL,
	"ANS_CONTENT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "ANSWER_DETAIL_LEADERSHIP"."ANS_L_ID" IS '응답한 사람이 리더십에 대한 어떤 대답';

COMMENT ON COLUMN "ANSWER_DETAIL_LEADERSHIP"."ANSWER_ID" IS '응답한사람';

COMMENT ON COLUMN "ANSWER_DETAIL_LEADERSHIP"."QUESTION_ID" IS '방장의 리더십은?';

COMMENT ON COLUMN "ANSWER_DETAIL_LEADERSHIP"."ANS_CONTENT" IS '1,0,-1';

CREATE TABLE "DELETED_RIDING" (
	"DEL_RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"RIDING_ID"	VARCHAR2(30)		NOT NULL,
	"DELETE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "DELETED_RIDING"."DEL_RIDING_ID" IS '모임 삭제하면 여기에';

COMMENT ON COLUMN "DELETED_RIDING"."RIDING_ID" IS '모임 ID';

COMMENT ON COLUMN "DELETED_RIDING"."DELETE_DATE" IS '모임 삭제일';

CREATE TABLE "ABSCOND" (
	"ABSCOND_ID"	VARCHAR2(30)		NOT NULL,
	"P_MEMBER_ID"	VARCHAR2(30)		NOT NULL,
	"ABSCOND_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "ABSCOND"."ABSCOND_ID" IS '시퀀스ID';

COMMENT ON COLUMN "ABSCOND"."P_MEMBER_ID" IS '테이블 시퀀스 ID';

COMMENT ON COLUMN "ABSCOND"."ABSCOND_DATE" IS '이탈한 날짜, 참여자 리스트에서 DEL은 아님';

CREATE TABLE "INQUIRY_PROCESS_STATUS" (
	"INQUIRY_STATUS_ID"	NUMBER(1)		NOT NULL,
	"CONTENT"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "INQUIRY_PROCESS_STATUS"."INQUIRY_STATUS_ID" IS '문의 처리에 대한 분류 범례';

COMMENT ON COLUMN "INQUIRY_PROCESS_STATUS"."CONTENT" IS '1. 해결 2.반려';




