/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-05 16:21:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mj;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class JoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JoinForm.jsp</title>\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.joinFormBox\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth: 600px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.joinBtn\r\n");
      out.write("\t{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"joinFormBox\">\r\n");
      out.write("\t<form action=\"\" class=\"joinForm\">\r\n");
      out.write("\t\t<div class=\"form-group form-inline\">\r\n");
      out.write("\t\t\t<label for=\"inputNickname\">닉네임</label>\r\n");
      out.write("\t    \t<input type=\"email\" class=\"form-control\" id=\"inputNickname\" placeholder=\"닉네임을 입력하세요\">\r\n");
      out.write("\t    \t<input type=\"button\" class=\"btn btn-default\" value=\"중복 확인\"/>\r\n");
      out.write("\t    \t<br /><span>12자 이내의 닉네임을 입력하세요.</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<div class=\"form-group form-inline\">\r\n");
      out.write("\t\t\t<label for=\"inputEmail\">이메일</label>\r\n");
      out.write("\t    \t<input type=\"email\" class=\"form-control\" id=\"inputEmail\" placeholder=\"이메일을 입력하세요\">\r\n");
      out.write("\t\t\t<select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t<option value=\"네이버\">@naver.com</option>\r\n");
      out.write("\t\t\t\t<option value=\"구글\">@google.com</option>\r\n");
      out.write("\t\t\t\t<option value=\"네이트\">@nate.com</option>\r\n");
      out.write("\t\t\t</select>    \r\n");
      out.write("\t\t\t<br /><span>등록하신 이메일은 로그인 시 아이디로 사용됩니다.</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group form-inline\">\r\n");
      out.write("\t    \t<label for=\"inputPassword\">비밀번호</label>\r\n");
      out.write("\t    \t<input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"비밀번호를 입력하세요\"/>\r\n");
      out.write("\t    \t<br /><span>8~12자 이내의 비밀번호를 입력하세요.</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"form-group form-inline\">\r\n");
      out.write("\t    \t<label for=\"\">생년월일</label>\r\n");
      out.write("\t    \t<select name=\"birthyear\" id=\"birthyear\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t<option value=\"year\">1999</option>\r\n");
      out.write("\t\t\t\t<option value=\"year\">2000</option>\r\n");
      out.write("\t\t\t\t<option value=\"year\">2001</option>\r\n");
      out.write("\t\t\t</select>년\r\n");
      out.write("\t\t\t<select name=\"birthmonth\" id=\"birthmonth\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t<option value=\"month\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"month\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"month\">3</option>\r\n");
      out.write("\t\t\t</select>월\r\n");
      out.write("\t\t\t<select name=\"birthday\" id=\"birthday\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t<option value=\"day\">1</option>\r\n");
      out.write("\t\t\t\t<option value=\"day\">2</option>\r\n");
      out.write("\t\t\t\t<option value=\"day\">3</option>\r\n");
      out.write("\t\t\t</select>일\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<div class=\"form-group form-inline\">\r\n");
      out.write("\t\t\t<label for=\"gender\">성별</label>\r\n");
      out.write("\t\t\t<select name=\"gender\" id=\"gender\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t<option value=\"male\">남성</option>\r\n");
      out.write("\t\t\t\t<option value=\"female\">여성</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<h3>라이딩 스타일 <small>마이페이지에서 수정할 수 있습니다.</small></h3>\r\n");
      out.write("\t\t\t<label for=\"gender\" class=\"\">성별</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender\" value=\"male\"/>남성\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" id=\"gender\" value=\"female\"/>여성\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"age\">연령대</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"20\"/>20대\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"30\"/>30대\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"40\"/>40대\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"50\"/>50대\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"age\" id=\"age\" value=\"60\"/>60대 이상\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"speed\">속도</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"speed\" id=\"speed\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"speed\" id=\"speed\" value=\"20미만\"/>20미만\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"speed\" id=\"speed\" value=\"20이상 24미만\"/>20이상 24미만\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"speed\" id=\"speed\" value=\"24이상\"/>24이상\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"step\">숙련도</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"step\" id=\"step\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"step\" id=\"step\" value=\"1년 미만\" />1년 미만\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"step\" id=\"step\" value=\"1~3년\" />1~3년\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"step\" id=\"step\" value=\"3~5년\" />3~5년\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"step\" id=\"step\" value=\"6년 이상\" />6년 이상\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"eat\">식사 여부</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"eat\" id=\"eat\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"eat\" id=\"eat\" value=\"밥 안 먹고 달려요\"/>밥 안 먹고 달려요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"eat\" id=\"eat\" value=\"밥 먹고 달려요\"/>밥 먹고 달려요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"dinning\">회식 여부</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"dinning\" id=\"dinning\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"dinning\" id=\"dinning\" value=\"끝나고 회식 안 해요\"/>끝나고 회식 안 해요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"dinning\" id=\"dinning\" value=\"끝나고 회식해요\"/>끝나고 회식해요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t<label for=\"mood\">분위기</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"mood\" id=\"mood\" value=\"nolimit\" checked=\"checked\"> 제한 없음\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"mood\" id=\"mood\" value=\"침묵이 좋아요\"/>침묵이 좋아요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t\t<label class=\"radio-inline\">\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"mood\" id=\"mood\" value=\"친목이 좋아요\"/>친목이 좋아요\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group joinBtn\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\" value=\"회원가입\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
