/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-06-05 16:21:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mj;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RidingList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>RidingList.jsp</title>\r\n");
      out.write("<!-- 제이쿼리 -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("\t<div>모임명</div>\r\n");
      out.write("\t<input type=\"text\" />\r\n");
      out.write("\t<input type=\"button\" value=\"찾기\"/>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li> 연령대\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"전체\">전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"10대\">10대</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"20대\">20대</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"30대\">30대</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"40대\">40대</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"50대\">50대</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"age\" value=\"60대 이상\"> 60대 이상</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 성별\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"gender\" value=\"전체\"/>전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"gender\" value=\"남성\"/>남성</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"gender\" value=\"여성\"/>여성</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 속도\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"speed\" value=\"전체\"/>전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"speed\" value=\"20미만\"/>20미만</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"speed\" value=\"20이상 24미만\"/>20이상 24미만</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"speed\" value=\"24이상\"/>24이상</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 숙련도\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"step\" value=\"전체\"/>전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"step\" value=\"1년 미만\"/>1년 미만</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"step\" value=\"1~3년\"/>1~3년</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"step\" value=\"3~5년\"/>3~5년</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"step\" value=\"6년 이상\"/>6년 이상</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 회식 여부\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"dinning\" value=\"전체\"/>전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"dinning\" value=\"끝나고 회식해요\"/>끝나고 회식해요</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"dinning\" value=\"끝나고 회식 안 해요\"/>끝나고 회식 안 해요</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 식사 여부\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"eat\" value=\"전체\"/>전체</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"eat\" value=\"밥 먹고 달려요\"/>밥 먹고 달려요</label>\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"eat\" value=\"밥 안 먹고 달려요\"/>밥 안 먹고 달려요</label>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 분위기\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"mood\" value=\"전체\"/>전체</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"mood\" value=\"침묵이 좋아요\"/>침묵이 좋아요</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"mood\" value=\"친목이 좋아요\"/>친목이 좋아요</label> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li> 제한 등급\r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"전체\"/>전체</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"다이아전거\"/>다이아전거</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"금전거\"/>금전거</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"은전거\"/>은전거</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"동전거\"/>동전거</label> \r\n");
      out.write("\t\t<label><input type=\"checkbox\" name=\"grade\" value=\"돌전거\"/>돌전거</label> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li><input type=\"button\" value=\"나의 라이딩 스타일 적용\"/></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>모임명</th>\r\n");
      out.write("\t\t\t<th>최대</th>\r\n");
      out.write("\t\t\t<th>참여가능</th>\r\n");
      out.write("\t\t\t<th>기간</th>\r\n");
      out.write("\t\t\t<th>참석가능여부</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>인천 피플</td>\r\n");
      out.write("\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>2022.06.20 12:00 ~ 2022.06.20 16:00</td>\r\n");
      out.write("\t\t\t<td>참석 가능\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"신고\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>인천 피플</td>\r\n");
      out.write("\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>2022.06.20 12:00 ~ 2022.06.20 16:00</td>\r\n");
      out.write("\t\t\t<td>참석 가능\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"신고\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>인천 피플</td>\r\n");
      out.write("\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>2022.06.20 12:00 ~ 2022.06.20 16:00</td>\r\n");
      out.write("\t\t\t<td>참석 가능\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"신고\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>인천 피플</td>\r\n");
      out.write("\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>2022.06.20 12:00 ~ 2022.06.20 16:00</td>\r\n");
      out.write("\t\t\t<td>참석 가능\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"신고\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>인천 피플</td>\r\n");
      out.write("\t\t\t<td>9</td>\r\n");
      out.write("\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t<td>2022.06.20 12:00 ~ 2022.06.20 16:00</td>\r\n");
      out.write("\t\t\t<td>참석 가능\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"신고\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"button\" value=\"라이딩 모임 만들기\"/>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
